// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANZ8agcj7oG6dsyZGQZqTqk9aZKJ2Gxgw',
    appId: '1:846785435201:web:40f5cc7975aae1c794d8c0',
    messagingSenderId: '846785435201',
    projectId: 'cars-96b4e',
    authDomain: 'cars-96b4e.firebaseapp.com',
    storageBucket: 'cars-96b4e.appspot.com',
    measurementId: 'G-07P07H8997',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2e-4xSwrutvpfHkRn5wjsJBPXZ4etLB0',
    appId: '1:846785435201:android:2737b438152b13d894d8c0',
    messagingSenderId: '846785435201',
    projectId: 'cars-96b4e',
    storageBucket: 'cars-96b4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-4cimzShuMX7bXj9-BRtQadOdTt3fkH0',
    appId: '1:846785435201:ios:3ce0a5683d22f9e294d8c0',
    messagingSenderId: '846785435201',
    projectId: 'cars-96b4e',
    storageBucket: 'cars-96b4e.appspot.com',
    iosBundleId: 'com.example.vin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-4cimzShuMX7bXj9-BRtQadOdTt3fkH0',
    appId: '1:846785435201:ios:3ce0a5683d22f9e294d8c0',
    messagingSenderId: '846785435201',
    projectId: 'cars-96b4e',
    storageBucket: 'cars-96b4e.appspot.com',
    iosBundleId: 'com.example.vin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANZ8agcj7oG6dsyZGQZqTqk9aZKJ2Gxgw',
    appId: '1:846785435201:web:ae5635b6031344a194d8c0',
    messagingSenderId: '846785435201',
    projectId: 'cars-96b4e',
    authDomain: 'cars-96b4e.firebaseapp.com',
    storageBucket: 'cars-96b4e.appspot.com',
    measurementId: 'G-H2ZWGNSKF6',
  );

}